---
  - name: Local redis data directory
    file:
      path: /var/lib/redis/data
      state: directory

  - name: Redis container
    docker_container:
      name: redis
      image: redis:3.2.6
      state: started
      restart_policy: on-failure
      restart_retries: 5
      volumes:
        - "/var/lib/redis/data:/data"
      log_driver: journald
