---
- name: all
  hosts: all
  roles:
    - users
    - apt
    - hostname
    - docker
    - postgres
    - redis
    - firewall
    - danpalmer
    - petitions
    - nginx
    - prometheus
    - grafana
    - nodeexporter
    - cadvisor
    - monzo
