---
  - name: Check existence of TLS certificate
    stat:
      path: /etc/letsencrypt/live/monzo.danpalmer.me/fullchain.pem
    register: monzo_certificate
    tags:
      - monzo-deploy

  - name: monzo.danpalmer.me web container
    docker_container:
      name: monzo
      image: danpalmer/monzo-web
      restart: true
      state: started
      pull: true
      restart_policy: on-failure
      restart_retries: 5
      ports:
        - "8006:80"
      log_driver: journald
    tags:
      - monzo-deploy

  - name: monzo.danpalmer.me nginx configuration
    template:
      src: monzo.danpalmer.me.conf
      dest: /etc/nginx/sites-enabled/monzo.danpalmer.me
      mode: 0644
    tags:
      - monzo-deploy
    notify:
      - add missing tls certs
      - restart nginx
