---

- name: checkout application if not already existing
  git: repo={{code_repository}} dest={{app_code_dir}} force=yes depth=1
  sudo: yes
  sudo_user: deploy
  notify:
    - restart supervisor

- name: install web application dependencies listed in requirements.txt
  pip: requirements={{requirements_file}}
       virtualenv={{virtualenv_dir}}

- name: Django collectstatic
  django_manage: command=collectstatic
                 app_path={{app_code_dir}}
                 virtualenv={{virtualenv_dir}}
                 settings={{django_settings}}
  environment: django_env_vars

- name: Django migrate
  django_manage: command=migrate
                 app_path={{app_code_dir}}
                 virtualenv={{virtualenv_dir}}
                 settings={{django_settings}}
  environment: django_env_vars

# - name: Django loaddata
#   django_manage: command=loaddata
#                  app_path={{app_code_dir}}
#                  virtualenv={{virtualenv_dir}}
#                  fixtures={{fixtures_file}}
#                  settings={{django_settings}}
#   environment: django_env_vars
