---
  - name: Install UFW
    apt:
      pkg: ufw
      state: latest
      update_cache: yes
      cache_valid_time: 86400

  - name: Enable UFW rejecting by default
    ufw:
      state: enabled
      policy: deny

  - name: Allow SSH
    ufw:
      rule: allow
      name: OpenSSH

  - name: Allow HTTP(S)
    ufw:
      rule: allow
      port: "{{ item }}"
    with_items:
      - 80
      - 443
