---
  - name: Install UFW
    apt:
      pkg: ufw
      state: latest
      update_cache: yes
      cache_valid_time: 86400

  - name: Enable UFW
    ufw:
      state: enabled

  - name: Allow SSH
    ufw:
      rule: allow
      name: OpenSSH

  - name: Allow HTTP(S)
    ufw:
      rule: allow
      port: "{{ item }}"
      proto: tcp
    with_items:
      - 80
      - 443

  - name: Reject by default
    become_user: root
    become_method: sudo
    ufw:
      policy: reject

