---

- name: write dhparams
  template: src=dhparam.pem dest=/etc/ssl/certs/dhparam.pem
  sudo: yes
  when: deploy_ssl
  notify:
    - restart nginx

- name: write SSL nginx configuration
  template: src=nginx_ssl.conf.j2 dest=/etc/nginx/conf.d/{{app_name}}.conf
  sudo: yes
  when: deploy_ssl
  notify:
    - restart nginx

- name: write non-SSL nginx configuration
  template: src=nginx_no_ssl.conf.j2 dest=/etc/nginx/conf.d/{{app_name}}.conf
  sudo: yes
  when: not deploy_ssl
  notify:
    - restart nginx

- name: check if nginx has default symbolic linked website file
  stat: path=/etc/nginx/sites-enabled/default
  register: nginx_default_file

- name: delete default symbolic linked website on nginx
  command: rm /etc/nginx/sites-enabled/default
  sudo: yes
  when: nginx_default_file.stat.exists
  notify:
    - restart nginx

