###
# updates the APT package cache and install packages necessary for web
# servers
#
---

- name: ensure apt cache is up to date
  apt: update_cache=yes
  sudo: yes

- name: ensure web server packages are installed
  apt: name={{item}}
  sudo: yes
  with_items:
    - git
    - python3-dev
    - libpq-dev
    - libffi-dev
    - python-virtualenv
    - nginx
    - supervisor
    - postgresql-client-common
    - postgresql-client
    - libcairo2
    - libpango1.0-0
    - libgdk-pixbuf2.0-0
    - shared-mime-info
    - python-gtk2
