---
  - name: Install dependencies
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
      - python
      - python-setuptools

  - name: Install pip
    easy_install:
      name=pip

  - name: Install docker-py
    pip:
      name: docker-py
      state: present
      version: 1.1.0

  - name: Add docker apt repo
    apt_repository:
      repo: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"
      state: present

  - name: Import the Docker repository key
    apt_key:
      url: https://apt.dockerproject.org/gpg
      state: present
      id: 2C52609D

  - name: Install dmsetup
    apt:
      name: dmsetup
      state: present

  - name: dmsetup mknodes - for Docker
    command: dmsetup mknodes

  - name: Install Docker package
    apt:
      name: docker-engine
      update_cache: yes
      state: latest

  - name: Add Docker environment file
    copy:
      src: docker_config
      dest: /etc/default/docker
      mode: 0644
    notify:
      restart docker

  - name: Ensure /etc/systemd/system/docker.service.d dir exists
    file:
      path: /etc/systemd/system/docker.service.d
      state: directory

  - name: Add systemd override for EnvironmentFile
    copy:
      src: override-docker.conf
      dest: /etc/systemd/system/docker.service.d/override-docker.conf
      mode: 0644
    notify:
      restart docker

  - name: Docker UI
    docker:
      name: dockerui
      image: kevan/dockerui
      privileged: yes
      state: reloaded
      pull: always
      restart_policy: on-failure
      restart_policy_retry: 5
      ports:
        - "8001:9000"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
