---
  - name: Install dependencies
    apt:
      name: "{{ item }}"
      update_cache: yes
    with_items:
      - python
      - python-setuptools

  - name: Install pip
    easy_install:
      name=pip

  - name: Install Aufs
    shell: sudo apt-get install linux-image-extra-$(uname -r) linux-image-extra-virtual

  - name: Install docker-py
    pip:
      name: docker-py
      state: present
      version: 1.10.6

  - name: Add docker apt repo
    apt_repository:
      repo: "deb https://apt.dockerproject.org/repo ubuntu-xenial main"
      state: present

  - name: Import the Docker repository key
    apt_key:
      url: https://apt.dockerproject.org/gpg
      state: present
      id: 2C52609D

  - name: Install dmsetup
    apt:
      name: dmsetup
      state: present

  - name: dmsetup mknodes - for Docker
    command: dmsetup mknodes

  - name: Install Docker package
    apt:
      name: docker-engine
      update_cache: yes
      state: latest

  - name: Add Docker environment file
    copy:
      src: docker_config
      dest: /etc/default/docker
      mode: 0644
    notify:
      restart docker

  - name: Ensure /etc/systemd/system/docker.service.d dir exists
    file:
      path: /etc/systemd/system/docker.service.d
      state: directory

  - name: Add systemd override for EnvironmentFile
    copy:
      src: override-docker.conf
      dest: /etc/systemd/system/docker.service.d/override-docker.conf
      mode: 0644
    notify:
      restart docker

  - name: Docker UI
    docker_container:
      name: dockerui
      image: kevan/dockerui
      privileged: yes
      restart: true
      state: started
      pull: true
      restart_policy: always
      restart_retries: 5
      ports:
        - "127.0.0.1:8001:9000"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
      log_driver: journald

  - name: Docker UI nginx configuration
    copy:
      src: dockerui.nginx.conf
      dest: /etc/nginx/sites-enabled/docker.danpalmer.me
      mode: 0644
    notify:
      restart nginx
