---
  - name: Local postgres data directory
    file:
      path: /var/lib/postgresql/data
      state: directory

  - name: Postgres container
    docker_container:
      name: postgres
      image: postgres:9.5.2
      state: started
      restart_policy: always
      restart_retries: 5
      env:
        POSTGRES_PASSWORD: "{{ database_password }}"
      volumes:
        - "/var/lib/postgresql/data:/var/lib/postgresql/data"
      log_driver: journald
